Script started on Tue 21 Oct 2014 10:39:39 PM PDT
]0;mevans@localhost:~/bridget/rshell]7;file://localhost.localdomain/home/mevans/bridget/rshell[?1034h[mevans@localhost rshell]$ ls && ls -a #demonstrainting that spaces don't matter[1P[1P[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kbin/rshell
mevans@localhost.localdomain$ ls && ls-  -a #Demonstrating that spaces don't matter with connectors
bin  LICENSE  Makefile	README.md  src	tests
.  ..  bin  .git  LICENSE  Makefile  README.md	src  tests
mevans@localhost.localdomain$ ls&&ls -a
bin  LICENSE  Makefile	README.md  src	tests
.  ..  bin  .git  LICENSE  Makefile  README.md	src  tests
mevans@localhost.localdomain$ ls
bin  LICENSE  Makefile	README.md  src	tests
mevans@localhost.localdomain$ pwd
/home/mevans/bridget/rshell
mevans@localhost.localdomain$ ls -a -l -h -F R src #Large number of arguments
.  ..  bin  .git  LICENSE  Makefile  README.md	src  tests
mevans@localhost.localdomain$ ls && pwd && echo This works #&& works when all wori    work
bin  LICENSE  Makefile	README.md  src	tests
/home/mevans/bridget/rshell
This works
mevans@localhost.localdomain$ ls && pdw && echo This won't print #Logic works
bin  LICENSE  Makefile	README.md  src	tests
execvp: No such file or directory
mevans@localhost.localdomain$ sl || pdw || ls || pwd
execvp: No such file or directory
execvp: No such file or directory
bin  LICENSE  Makefile	README.md  src	tests
mevans@localhost.localdomain$ ls; pwd; ls -a
bin  LICENSE  Makefile	README.md  src	tests
/home/mevans/bridget/rshell
.  ..  bin  .git  LICENSE  Makefile  README.md	src  tests
mevans@localhost.localdomain$ bin/rshell #Call      Run itself
mevans@localhost.localdomain$ echo I'm inside myself!
I'm inside myself!
mevans@localhost.localdomain$ exit #exit command works
mevans@localhost.localdomain$ echo first; ls;echo listed ; ls -a;echo listed all ;pwd ;echo current directory #large number of commands
first
bin  LICENSE  Makefile	README.md  src	tests
listed
.  ..  bin  .git  LICENSE  Makefile  README.md	src  tests
listed all
/home/mevans/bridget/rshell
current directory
mevans@localhost.localdomain$ Echo capitol #won't run wi               #case sensitive
execvp: No such file or directory
mevans@localhost.localdomain$ cd .. #Shouldn't work
mevans@localhost.localdomain$ ls
bin  LICENSE  Makefile	README.md  src	tests
mevans@localhost.localdomain$ ls;
execvp: No such file or directory
mevans@localhost.localdomain$ ls ||
bin  LICENSE  Makefile	README.md  src	tests
mevans@localhost.localdomain$ ls &&
bin  LICENSE  Makefile	README.md  src	tests
mevans@localhost.localdomain$ exit
]0;mevans@localhost:~/bridget/rshell]7;file://localhost.localdomain/home/mevans/bridget/rshell[mevans@localhost rshell]$ bin/rshell
mevans@localhost.localdomain$ exit;
execvp: No such file or directory
mevans@localhost.localdomain$ w exit ||
mevans@localhost.localdomain$ exit ;
]0;mevans@localhost:~/bridget/rshell]7;file://localhost.localdomain/home/mevans/bridget/rshell[mevans@localhost rshell]$ exit
exit

Script done on Tue 21 Oct 2014 10:50:15 PM PDT
